/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenii_p2_luismendoza;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author luiscarlomendoza
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public void ActualizarArbol(ArrayList<Deporte> lista, DefaultMutableTreeNode nodo) {
        if (lista.isEmpty() == false) {
            for (Deporte f : lista) {
                DefaultMutableTreeNode n1 = new DefaultMutableTreeNode(f);
                nodo.add(n1);
            }
        }
    }

    public void Tabla() {

        DefaultTableModel tablaEquipos = new DefaultTableModel();
        tablaEquipos.addColumn("Nombre");
        tablaEquipos.addColumn("Puntos");

        for (int i = 0; i < deportes.size(); i++) {
            for (int j = 0; j < deportes.get(i).getTorneos().size(); j++) {
                if (deportes.get(i).getTorneos().get(j).equals(torneo_seleccionado)) {
                    for (int k = 0; k < deportes.get(i).getTorneos().get(j).getEquipos().size(); k++) {
                        tablaEquipos.addRow(new Object[]{
                            deportes.get(i).getTorneos().get(j).getEquipos().get(k).getNombre(),
                            deportes.get(i).getTorneos().get(j).getEquipos().get(k).getPuntos()
                        });
                    }

                }
            }

        }
        jTable1.setModel(tablaEquipos);

    }

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_popup = new javax.swing.JPopupMenu();
        jmi_AgregarTorneo = new javax.swing.JMenuItem();
        menu_popupTorneo = new javax.swing.JPopupMenu();
        Agregar_Equipo = new javax.swing.JMenuItem();
        Listar_Equipo = new javax.swing.JMenuItem();
        Registrar_Resultado = new javax.swing.JMenuItem();
        Tabla_Posiciones = new javax.swing.JMenuItem();
        jd_listarEquipos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jd_registrarResultado = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_equipos1 = new javax.swing.JComboBox<>();
        js_1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        cb_equipos2 = new javax.swing.JComboBox<>();
        js_2 = new javax.swing.JSpinner();
        jb_registrarResultado = new javax.swing.JButton();
        jd_tablaDeResultados = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cargar = new javax.swing.JButton();

        jmi_AgregarTorneo.setText("Agregar Torneo");
        jmi_AgregarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AgregarTorneoActionPerformed(evt);
            }
        });
        menu_popup.add(jmi_AgregarTorneo);

        Agregar_Equipo.setText("Agregar Equipo");
        Agregar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_EquipoActionPerformed(evt);
            }
        });
        menu_popupTorneo.add(Agregar_Equipo);

        Listar_Equipo.setText("Listar Equipos");
        Listar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listar_EquipoActionPerformed(evt);
            }
        });
        menu_popupTorneo.add(Listar_Equipo);

        Registrar_Resultado.setText("Registrar Resultado");
        Registrar_Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_ResultadoActionPerformed(evt);
            }
        });
        menu_popupTorneo.add(Registrar_Resultado);

        Tabla_Posiciones.setText("Tabla de Resultados");
        Tabla_Posiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tabla_PosicionesActionPerformed(evt);
            }
        });
        menu_popupTorneo.add(Tabla_Posiciones);

        jd_listarEquipos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Wawati TC", 0, 24)); // NOI18N
        jLabel2.setText("Lista de Equipos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jd_listarEquipos.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 390));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Wawati TC", 0, 24)); // NOI18N
        jLabel5.setText("Lista de Partidos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jd_listarEquipos.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 380, 390));

        jd_registrarResultado.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Weibei TC", 0, 24)); // NOI18N
        jLabel3.setText("Registrar Resultado");

        js_1.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cb_equipos1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(js_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(cb_equipos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(js_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jd_registrarResultado.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 470));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));

        js_2.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        jb_registrarResultado.setText("Registrar");
        jb_registrarResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_registrarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarResultadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cb_equipos2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(js_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jb_registrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(cb_equipos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(js_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jb_registrarResultado)
                .addGap(115, 115, 115))
        );

        jd_registrarResultado.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 280, 470));

        jPanel7.setBackground(new java.awt.Color(255, 0, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Wawati SC", 0, 24)); // NOI18N
        jLabel4.setText("Tabla de Resultados");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_tablaDeResultadosLayout = new javax.swing.GroupLayout(jd_tablaDeResultados.getContentPane());
        jd_tablaDeResultados.getContentPane().setLayout(jd_tablaDeResultadosLayout);
        jd_tablaDeResultadosLayout.setHorizontalGroup(
            jd_tablaDeResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_tablaDeResultadosLayout.setVerticalGroup(
            jd_tablaDeResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jLabel1.setFont(new java.awt.Font("Wawati SC", 0, 36)); // NOI18N
        jLabel1.setText("Deportes UNITEC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 450, 450));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jButton1.setText("Agregar Deporte");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jb_guardar.setText("Guardar");
        jb_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        jb_cargar.setText("Cargar");
        jb_cargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jb_guardar)
                .addGap(18, 18, 18)
                .addComponent(jb_cargar)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del deporte");
        String periodo = JOptionPane.showInputDialog("Ingrese el periodo");

        Deporte deporte = new Deporte(nombre, periodo);
        deportes.add(deporte);

        DefaultTreeModel mClean = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode raizClean = (DefaultMutableTreeNode) mClean.getRoot();
        DefaultMutableTreeNode qq1 = (DefaultMutableTreeNode) raizClean.getChildAt(0);
        DefaultMutableTreeNode qq2 = (DefaultMutableTreeNode) raizClean.getChildAt(1);
        DefaultMutableTreeNode qq4 = (DefaultMutableTreeNode) raizClean.getChildAt(2);
        DefaultMutableTreeNode qq5 = (DefaultMutableTreeNode) raizClean.getChildAt(3);

        qq1.removeAllChildren();
        qq2.removeAllChildren();
        qq4.removeAllChildren();
        qq5.removeAllChildren();

        mClean.reload();

        DefaultTreeModel m = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q5 = (DefaultMutableTreeNode) raiz.getChildAt(3);

        ActualizarArbol(deportes, q1);
        ActualizarArbol(deportes, q2);
        ActualizarArbol(deportes, q4);
        ActualizarArbol(deportes, q5);

        m.reload();


    }//GEN-LAST:event_jButton1MouseClicked

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:

        if (evt.getButton() == 3) {
            //seleccionar un nodo con click derecho
            int row = jTree1.getClosestRowForLocation(evt.getX(), evt.getY());
            jTree1.setSelectionRow(row);
            Object v1 = jTree1.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Deporte) {
                deporte_seleccionada = (Deporte) nodo_seleccionado.getUserObject();
                menu_popup.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Torneo) {
                torneo_seleccionado = (Torneo) nodo_seleccionado.getUserObject();
                menu_popupTorneo.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }

    }//GEN-LAST:event_jTree1MouseClicked

    private void jmi_AgregarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AgregarTorneoActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del torneo");
        Torneo torneo = new Torneo(nombre);
        for (int i = 0; i < deportes.size(); i++) {
            if (deporte_seleccionada.equals(deportes.get(i))) {
                deportes.get(i).getTorneos().add(torneo);
                for (int j = 0; j < deportes.get(i).getTorneos().size(); j++) {
                    if (deportes.get(i).getTorneos().get(j).equals(torneo)) {
                        DefaultMutableTreeNode t = new DefaultMutableTreeNode(deportes.get(i).getTorneos().get(j));
                        nodo_seleccionado.add(t);
                    }
                }

            }
        }


    }//GEN-LAST:event_jmi_AgregarTorneoActionPerformed

    private void Agregar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_EquipoActionPerformed
        // TODO add your handling code here:

        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del equipo");
        int puntos = 0;

        Equipo equipo = new Equipo(nombre, puntos);

        for (int i = 0; i < deportes.size(); i++) {
            for (int j = 0; j < deportes.get(i).getTorneos().size(); j++) {
                if (deportes.get(i).getTorneos().get(j).equals(torneo_seleccionado)) {
                    deportes.get(i).getTorneos().get(j).getEquipos().add(equipo);
                }
            }
        }


    }//GEN-LAST:event_Agregar_EquipoActionPerformed

    private void Listar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listar_EquipoActionPerformed
        // TODO add your handling code here:

        if (torneo_seleccionado.getEquipos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aun no hay equipos");
        } else {
            DefaultListModel clean = (DefaultListModel) jList1.getModel();
            clean.removeAllElements();
            jList1.setModel(clean);

            for (int i = 0; i < deportes.size(); i++) {
                for (int j = 0; j < deportes.get(i).getTorneos().size(); j++) {
                    if (deportes.get(i).getTorneos().get(j).equals(torneo_seleccionado)) {
                        DefaultListModel modelo = (DefaultListModel) jList1.getModel();
                        for (int k = 0; k < deportes.get(i).getTorneos().get(j).getEquipos().size(); k++) {
                            modelo.addElement(deportes.get(i).getTorneos().get(j).getEquipos().get(k));
                        }
                        jList1.setModel(modelo);
                    }
                }
            }

            jd_listarEquipos.setModal(true);
            jd_listarEquipos.pack();
            jd_listarEquipos.setLocationRelativeTo(this);
            jd_listarEquipos.setVisible(true);
        }


    }//GEN-LAST:event_Listar_EquipoActionPerformed

    private void Registrar_ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_ResultadoActionPerformed
        // TODO add your handling code here:

        if (torneo_seleccionado.getEquipos().size() < 2) {
            JOptionPane.showMessageDialog(this, "Se necesitan más equipos");
        } else {
            cb_equipos1.removeAllItems();
            cb_equipos2.removeAllItems();

            for (int i = 0; i < torneo_seleccionado.getEquipos().size(); i++) {
                cb_equipos1.addItem(torneo_seleccionado.getEquipos().get(i));
                cb_equipos2.addItem(torneo_seleccionado.getEquipos().get(i));
            }

            jd_registrarResultado.setModal(true);
            jd_registrarResultado.pack();
            jd_registrarResultado.setLocationRelativeTo(this);
            jd_registrarResultado.setVisible(true);
        }

    }//GEN-LAST:event_Registrar_ResultadoActionPerformed

    private void Tabla_PosicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabla_PosicionesActionPerformed
        // TODO add your handling code here:
        Tabla();
        jd_tablaDeResultados.setModal(true);
        jd_tablaDeResultados.pack();
        jd_tablaDeResultados.setLocationRelativeTo(this);
        jd_tablaDeResultados.setVisible(true);


    }//GEN-LAST:event_Tabla_PosicionesActionPerformed

    private void jb_registrarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarResultadoMouseClicked
        // TODO add your handling code here:
        Equipo equipo1 = (Equipo) cb_equipos1.getSelectedItem();
        Equipo equipo2 = (Equipo) cb_equipos2.getSelectedItem();
        int resultado1 = (Integer) js_1.getValue();
        int resultado2 = (Integer) js_2.getValue();

        Partido partido = new Partido(equipo1, equipo2, resultado1, resultado2);

        for (int i = 0; i < deportes.size(); i++) {
            for (int j = 0; j < deportes.get(i).getTorneos().size(); j++) {
                if (deportes.get(i).getTorneos().get(j).equals(torneo_seleccionado)) {
                    deportes.get(i).getTorneos().get(j).getPartidos().add(partido);
                    for (int k = 0; k < deportes.get(i).getTorneos().get(j).getEquipos().size(); k++) {
                        if (deportes.get(i).getTorneos().get(j).getEquipos().get(k).equals(equipo1)) {
                            if (resultado1 > resultado2) {
                                deportes.get(i).getTorneos().get(j).getEquipos().get(k).setPuntos(
                                        deportes.get(i).getTorneos().get(j).getEquipos().get(k).getPuntos() + 3);

                            } else if (resultado1 == resultado2) {
                                deportes.get(i).getTorneos().get(j).getEquipos().get(k).setPuntos(
                                        deportes.get(i).getTorneos().get(j).getEquipos().get(k).getPuntos() + 1);
                            }
                        } else if (deportes.get(i).getTorneos().get(j).getEquipos().get(k).equals(equipo2)) {
                            if (resultado1 < resultado2) {
                                deportes.get(i).getTorneos().get(j).getEquipos().get(k).setPuntos(
                                        deportes.get(i).getTorneos().get(j).getEquipos().get(k).getPuntos() + 3);
                            } else if (resultado1 == resultado2) {
                                deportes.get(i).getTorneos().get(j).getEquipos().get(k).setPuntos(
                                        deportes.get(i).getTorneos().get(j).getEquipos().get(k).getPuntos() + 1);
                            }
                        }
                    }
                }
            }

        }

        JOptionPane.showMessageDialog(jd_registrarResultado, "Se registro con éxito");


    }//GEN-LAST:event_jb_registrarResultadoMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:

        for (int i = 0; i < torneo_seleccionado.getPartidos().size(); i++) {
            if (torneo_seleccionado.getPartidos().get(i).getEquipo1().equals(jList1.getSelectedValue())) {
                jTextArea1.setText(torneo_seleccionado.getPartidos().get(i).toString());
            } else if (torneo_seleccionado.getPartidos().get(i).getEquipo2().equals(jList1.getSelectedValue())) {
                jTextArea1.setText(torneo_seleccionado.getPartidos().get(i).toString());
            }
        }


    }//GEN-LAST:event_jList1MouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int op = fc.showSaveDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivoOpen = fc.getSelectedFile();
            if (!archivoOpen.exists()) {
                archivoOpen = new File(archivoOpen.getPath() + ".cbm");
            } else {
                String[] path = archivoOpen.getPath().split("\\.");
                if (path[path.length - 1].equals("cbm")) {
                    try {
                        FileOutputStream fw = new FileOutputStream(archivoOpen);
                        ObjectOutputStream bw = new ObjectOutputStream(fw);
                        bw.writeObject((Deporte) deporte_seleccionada );
                        fw.close();
                        bw.close();
                        
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
        }

//        adminDeportes ad = new adminDeportes("./Deportes.cbm");
//        ad.setDeportes(deportes);
//        ad.escribirArchivo();


    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cargarMouseClicked
        // TODO add your handling code here:
//        adminDeportes ap = new adminDeportes("./Deportes.cbm");
//        ap.cargarArchivo();
//        deportes = ap.getDeportes();


    }//GEN-LAST:event_jb_cargarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar_Equipo;
    private javax.swing.JMenuItem Listar_Equipo;
    private javax.swing.JMenuItem Registrar_Resultado;
    private javax.swing.JMenuItem Tabla_Posiciones;
    private javax.swing.JComboBox<Equipo> cb_equipos1;
    private javax.swing.JComboBox<Equipo> cb_equipos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Equipo> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_registrarResultado;
    private javax.swing.JDialog jd_listarEquipos;
    private javax.swing.JDialog jd_registrarResultado;
    private javax.swing.JDialog jd_tablaDeResultados;
    private javax.swing.JMenuItem jmi_AgregarTorneo;
    private javax.swing.JSpinner js_1;
    private javax.swing.JSpinner js_2;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JPopupMenu menu_popupTorneo;
    // End of variables declaration//GEN-END:variables

    ArrayList<Deporte> deportes = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Deporte deporte_seleccionada;
    Torneo torneo_seleccionado;
    File archivoOpen;

}
